apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-staging
  namespace: uptime-${APPNAME}
spec:
  acme:
    # The ACME server URL
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: ${MYEMAIL}
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging
    # Enable the HTTP-01 challenge provider
    solvers:
    # An empty 'selector' means that this solver matches all domains
    - selector: {}
      http01:
        ingress:
          class: nginx

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod
  namespace: uptime-${APPNAME}
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: ${MYEMAIL}
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: nginx
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-${APPNAME}
  namespace: uptime-${APPNAME}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
  storageClassName: longhorn
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APPNAME}
  namespace: uptime-${APPNAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-uptime-${APPNAME}
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-uptime-${APPNAME}
    spec:
      containers:
      - image: louislam/uptime-kuma
        imagePullPolicy: IfNotPresent
        name: container-0
        ports:
        - containerPort: 3001
          name: ${APPNAME}
          protocol: TCP
        resources:
          requests:
            cpu: 50m
            memory: 16Mi
          limits:
            cpu: 1000m
            memory: 256Mi
        volumeMounts:
        - mountPath: /app/data
          name: ${APPNAME}
        - name: tz-config
          mountPath: /etc/localtime
      restartPolicy: Always
      volumes:
      - name: ${APPNAME}
        persistentVolumeClaim:
          claimName: pvc-${APPNAME}
      - name: tz-config
        hostPath:
           path: /usr/share/zoneinfo/Asia/Bangkok
           type: File
---
apiVersion: v1
kind: Service
metadata:
  name: ${APPNAME}
  namespace: uptime-${APPNAME}
spec:
  internalTrafficPolicy: Cluster
  ports:
  - name: ${APPNAME}
    port: 3001
    protocol: TCP
    targetPort: 3001
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-uptime-${APPNAME}
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
  # recommnet test with staging before prodution certificate
    cert-manager.io/issuer: letsencrypt-${CERTSTATE}
  name: ingress-${APPNAME}
  namespace: uptime-${APPNAME}
spec:
  ingressClassName: nginx
  rules:
  - host: ${APPNAME}.3.ipv9.xyz
    http:
      paths:
      - backend:
          service:
            name: ${APPNAME}
            port:
              number: 3001
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - ${APPNAME}.3.ipv9.xyz
    secretName: ${APPNAME}-3-ipv9-xyz-${CERTSTATE}-tls