apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-${APPNAME}
  namespace: uptime-${APPNAME}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APPNAME}
  namespace: uptime-${APPNAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-uptime-${APPNAME}
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-uptime-${APPNAME}
    spec:
      containers:
      - image: louislam/uptime-kuma
        imagePullPolicy: IfNotPresent
        name: container-0
        ports:
        - containerPort: 3001
          name: ${APPNAME}
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 16Mi
          limits:
            cpu: 2000m
            memory: 512Mi
        volumeMounts:
        - mountPath: /app/data
          name: ${APPNAME}
        - name: tz-config
          mountPath: /etc/localtime
      restartPolicy: Always
      volumes:
      - name: ${APPNAME}
        persistentVolumeClaim:
          claimName: pvc-${APPNAME}
      - name: tz-config
        hostPath:
           path: /usr/share/zoneinfo/Asia/Bangkok
           type: File

---
apiVersion: v1
kind: Service
metadata:
  name: ${APPNAME}
  namespace: uptime-${APPNAME}
spec:
  internalTrafficPolicy: Cluster
  ports:
  - name: ${APPNAME}
    port: 3001
    protocol: TCP
    targetPort: 3001
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-uptime-${APPNAME}
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-${APPNAME}
  namespace: uptime-${APPNAME}
spec:
  ingressClassName: nginx
  rules:
  - host: ${APPNAME}.3.ipv9.me
    http:
      paths:
      - backend:
          service:
            name: ${APPNAME}
            port:
              number: 3001
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - ${APPNAME}.3.ipv0.me